# # Use powerline
# USE_POWERLINE="true"
# # Has weird character width
# # Example:
# #    is not a diamond
# HAS_WIDECHARS="false"
# # Source manjaro-zsh-configuration
# if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
#   source /usr/share/zsh/manjaro-zsh-config
# fi
# # Use manjaro zsh prompt
# if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
#   source /usr/share/zsh/manjaro-zsh-prompt
# fi

# +---------+
# | HISTORY |
# +---------+

setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

fpath=($DOTFILES/zsh/plugins $fpath)

# +--------+
# | PROMPT |
# +--------+

fpath=($DOTFILES/zsh/prompts/pure $fpath)
fpath=($DOTFILES/zsh/prompts/powerlevel10k $fpath)

autoload -Uz promptinit
promptinit

prompt pure

# +-----------+
# | PROFILING |
# +-----------+

zmodload zsh/zprof

# +---------------------+
# | SYNTAX HIGHLIGHTING |
# +---------------------+

source $DOTFILES/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# +-----------------+
# | AUTOSUGGESTIONS |
# +-----------------+

source $DOTFILES/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# +--------+
# | COLORS |
# +--------+

# Override colors
eval "$(dircolors -b $ZDOTDIR/dircolors)"

# +---------+
# | ALIASES |
# +---------+

source $DOTFILES/aliases/aliases